### ISSUE TITLE
Error occures when trying to play with Agents

### ISSUE THREAD

**Issue by MiloTheFox** [Nilsen84/lunar_launcher_inject#3]
Whenever I try to play with Agents like the `HitDelayFix.jar` found at https://github.com/Nilsen84/lunar-client-agents/releases, it errors with the following:
```
[21:50:54] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Updating screen events
	at net.minecraft.client.Minecraft.runTick(SourceFile:1508) ~[?:?]
	at net.minecraft.client.Minecraft.runGameLoop(SourceFile:889) ~[?:?]
	at net.minecraft.client.Minecraft.run(SourceFile:325) [?:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at com.moonsworth.lunar.genesis.Genesis.main(Unknown Source) [genesis-0.1.0-SNAPSHOT-all.jar:?]
Caused by: java.lang.NoSuchMethodError: 'java.util.concurrent.atomic.AtomicIntegerFieldUpdater io.netty.util.internal.PlatformDependent.newAtomicIntegerFieldUpdater(java.lang.Class, java.lang.String)'
	at io.netty.util.concurrent.SingleThreadEventExecutor.<clinit>(SingleThreadEventExecutor.java:64) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:87) ~[?:?]
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:64) ~[?:?]
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:61) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:52) ~[?:?]
	at net.minecraft.network.NetworkSystem$1.load(SourceFile:44) ~[?:?]
	at net.minecraft.network.NetworkSystem$1.load(SourceFile:41) ~[?:?]
	at net.minecraft.util.LazyLoadBase.getValue(SourceFile:10) ~[?:?]
	at net.minecraft.network.NetworkSystem.addLocalEndpoint(SourceFile:121) ~[?:?]
	at net.minecraft.client.Minecraft.launchIntegratedServer(SourceFile:1942) ~[?:?]
	at net.minecraft.client.gui.GuiCreateWorld.actionPerformed(SourceFile:210) ~[?:?]
	at net.minecraft.client.gui.GuiScreen.redirect$zdj000$impl$onMouseClicked(SourceFile:1278) ~[?:?]
	at net.minecraft.client.gui.GuiScreen.mouseClicked(SourceFile:350) ~[?:?]
	at net.minecraft.client.gui.GuiCreateWorld.mouseClicked(SourceFile:350) ~[?:?]
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(SourceFile:413) ~[?:?]
	at net.minecraft.client.gui.GuiScreen.handleInput(SourceFile:390) ~[?:?]
	at net.minecraft.client.Minecraft.runTick(SourceFile:1498) ~[?:?]
	... 8 more
```

But when I play without any Agents, it works without any issues.

**Comment by MiloTheFox** [comment]
Here's what the Folder looks like:

![image](https://user-images.githubusercontent.com/80362356/218337082-19a2e74b-bfe4-403c-a78b-0723a68fd166.png)

**Comment by Monmcgt** [comment]
Do you have the same problem with other agents?

**Comment by MiloTheFox** [comment]
No, every other Agent works without any issues.

**Comment by Monmcgt** [comment]
Could you try to load HitDelayFix agent in [Youded-byte's lunar qt fork](https://github.com/Youded-byte/lunar-client-qt)? Does the game crash?

**Comment by MiloTheFox** [comment]
Yes it does. Here's the Error Stack from the error.log File:
```java
Exception in thread "main" java.nio.file.NoSuchFileException: .\Phosphor_v1_8.jar
	at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(Unknown Source)
	at java.base/java.nio.file.Files.readAttributes(Unknown Source)
	at java.base/java.util.zip.ZipFile$Source.get(Unknown Source)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	at java.base/java.util.jar.JarFile.<init>(Unknown Source)
	at java.base/java.util.jar.JarFile.<init>(Unknown Source)
	at java.base/java.util.jar.JarFile.<init>(Unknown Source)
	at com.moonsworth.lunar.ichor.OOIICIOOIORHCCOHOIRHCRCHI.OOIICIOOIORHCCOHOIRHCRCHI.ORRCICHIRHROCOCCICHCCCORI(Unknown Source)
	at com.moonsworth.lunar.ichor.IRROOIIOCHHOOOOIHCIRIOCRH.ORRCICHIRHROCOCCICHCCCORI(Unknown Source)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at com.moonsworth.lunar.ichor.IRROOIIOCHHOOOOIHCIRIOCRH.<init>(Unknown Source)
	at com.moonsworth.lunar.ichor.IRROOIIOCHHOOOOIHCIRIOCRH.<init>(Unknown Source)
	at com.moonsworth.lunar.ichor.IRROOIIOCHHOOOOIHCIRIOCRH.<init>(Unknown Source)
	at com.moonsworth.lunar.genesis.Genesis.main(Unknown Source)
```

**Comment by Monmcgt** [comment]
> Yes it does. Here's the Error Stack from the error.log File:
> 
> ```java
> Exception in thread "main" java.nio.file.NoSuchFileException: .\Phosphor_v1_8.jar
> 	at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
> 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
> 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
> 	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
> 	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
> 	at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(Unknown Source)
> 	at java.base/java.nio.file.Files.readAttributes(Unknown Source)
> 	at java.base/java.util.zip.ZipFile$Source.get(Unknown Source)
> 	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(Unknown Source)
> 	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
> 	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
> 	at java.base/java.util.jar.JarFile.<init>(Unknown Source)
> 	at java.base/java.util.jar.JarFile.<init>(Unknown Source)
> 	at java.base/java.util.jar.JarFile.<init>(Unknown Source)
> 	at com.moonsworth.lunar.ichor.OOIICIOOIORHCCOHOIRHCRCHI.OOIICIOOIORHCCOHOIRHCRCHI.ORRCICHIRHROCOCCICHCCCORI(Unknown Source)
> 	at com.moonsworth.lunar.ichor.IRROOIIOCHHOOOOIHCIRIOCRH.ORRCICHIRHROCOCCICHCCCORI(Unknown Source)
> 	at java.base/java.util.ArrayList.forEach(Unknown Source)
> 	at com.moonsworth.lunar.ichor.IRROOIIOCHHOOOOIHCIRIOCRH.<init>(Unknown Source)
> 	at com.moonsworth.lunar.ichor.IRROOIIOCHHOOOOIHCIRIOCRH.<init>(Unknown Source)
> 	at com.moonsworth.lunar.ichor.IRROOIIOCHHOOOOIHCIRIOCRH.<init>(Unknown Source)
> 	at com.moonsworth.lunar.genesis.Genesis.main(Unknown Source)
> ```

Follow Youded-byte/lunar-client-qt/issues/3 then try again. (or just rename multiver directory to anything else)

**Comment by MiloTheFox** [comment]
I did what it said (following the instructions in the guide) and it now works without any issues.

**Comment by Nilsen84** [comment]
do you have any other jar files in the directory? also from where did you get the log?

**Comment by MiloTheFox** [comment]
> do you have any other jar files in the directory? also from where did you get the log?

1. The Error Log is in the same Directory with the executable (using the Fork from Youded-byte, might I add).

![image](https://user-images.githubusercontent.com/80362356/218526827-86975522-5e18-4517-a285-e6541b7c88e7.png)

2. I only had the HitDelayFix jar file in the directory.
![image](https://user-images.githubusercontent.com/80362356/218526655-a3be8779-67bb-43a6-a47b-d30c5f1c1e37.png)

**Comment by Monmcgt** [comment]
> I did what it said (following the instructions in the guide) and it now works without any issues.

I'm glad to hear that.

Btw, could you run `tasklist /fi "imagename eq java.exe" /v` in a command prompt when the game (launched from lunar-launcher-inject) is running?

**Comment by MiloTheFox** [comment]
```java
Abbildname                     PID Sitzungsname       Sitz.-Nr. Speichernutzung Status          Benutzername                                           CPU-Zeit Fenstertitel
========================= ======== ================ =========== =============== =============== ================================================== ============ ========================================================================
javaw.exe                    12772 Console                    1     4.727.944 K Running         MS-7A38\*****                                     0:01:06 Lunar Client (1.8.9-e1dae3e/master)
```

**Comment by Monmcgt** [comment]
> ```java
> Abbildname                     PID Sitzungsname       Sitz.-Nr. Speichernutzung Status          Benutzername                                           CPU-Zeit Fenstertitel
> ========================= ======== ================ =========== =============== =============== ================================================== ============ ========================================================================
> javaw.exe                    12772 Console                    1     4.727.944 K Running         MS-7A38\*****                                     0:01:06 Lunar Client (1.8.9-e1dae3e/master)
> ```

Is there a `Command Line` column?

**Comment by Nilsen84** [comment]
closing due to inactivity
